DROP TABLE GRADE;
DROP TABLE COURSE;
DROP TABLE STUDENT;

CREATE TABLE STUDENT (
	ID SERIAL,
	LASTNAME  CHAR(35) NOT NULL DEFAULT 'DUPOND',
	FIRSTNAME CHAR(35) NOT NULL DEFAULT 'MonsieurMadame',
    AGE       NUMERIC(3)   NOT NULL DEFAULT 999,
	CONSTRAINT ID_STUDENT PRIMARY KEY (ID)
);

CREATE TABLE COURSE (
	ID SERIAL,
	LABEL CHAR(50) NOT NULL DEFAULT 'N/A',
	COEF  DECIMAL(2,1) NOT NULL DEFAULT 1.0,
	CONSTRAINT ID_COURSE PRIMARY KEY (ID)
);

CREATE TABLE GRADE (
	ID SERIAL,
	GRADE_STUDENT_ID NUMERIC(5),
	GRADE_COURSE_ID NUMERIC(5),
    LABEL CHAR(50) NOT NULL DEFAULT 'N/A',
    COEF DECIMAL(2,1) NOT NULL DEFAULT 1.0,
    GRADE DECIMAL(4,2) NOT NULL DEFAULT 99.99,
	CONSTRAINT ID_GRADE PRIMARY KEY (ID)
);

