CREATE TABLE OFFERS (
	off_id SMALLINT,
	off_name CHAR(50) NOT NULL DEFAULT 'Missing',
	off_price CHAR(10) NOT NULL DEFAULT '€99,99',
	CONSTRAINT id_offers PRIMARY KEY (off_id)
);

INSERT INTO OFFERS VALUES (1, 'Extract', '€52,10');
INSERT INTO OFFERS VALUES (2, 'Pepper', '€12,18');
INSERT INTO OFFERS VALUES (3, 'Split Peas', '€11,03');
INSERT INTO OFFERS VALUES (4, 'Rum', '€19,97');
INSERT INTO OFFERS VALUES (5, 'W Undercut', '€24,47');
INSERT INTO OFFERS VALUES (6, 'Bar Special', '€61,07');
INSERT INTO OFFERS VALUES (7, 'Macintosh', '€63,20');
INSERT INTO OFFERS VALUES (8, 'Lettuce', '€31,98');
INSERT INTO OFFERS VALUES (9, 'Sandwich', '€47,59');
INSERT INTO OFFERS VALUES (10, 'Sword', '€60,71');
INSERT INTO OFFERS VALUES (11, 'Energy', '€64,36');
INSERT INTO OFFERS VALUES (12, 'Wood Chips', '€12,03');
INSERT INTO OFFERS VALUES (13, 'Pepper ', '€70,66');
INSERT INTO OFFERS VALUES (14, 'Liqueur', '€38,66');
INSERT INTO OFFERS VALUES (15, 'Longos', '€44,43');
