DROP TABLE IF EXISTS GRADE;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS COURSE;

CREATE TABLE STUDENT
(
    ID        SERIAL PRIMARY KEY,
    LASTNAME  CHAR(35) NOT NULL DEFAULT 'DUPOND',
    FIRSTNAME CHAR(35) NOT NULL DEFAULT 'MonsieurMadame',
    AGE       NUMERIC(3) NOT NULL DEFAULT 99
); 


CREATE TABLE COURSE
(
    ID        SERIAL PRIMARY KEY,
    LABEL     CHAR(35) NOT NULL DEFAULT 'Manquant',
    COEF      NUMERIC(3,1) NOT NULL DEFAULT 1
);

CREATE TABLE GRADE
(
    ID SERIAL PRIMARY KEY,
    STUDENT_ID INTEGER NOT NULL,
    COURSE_ID INTEGER NOT NULL,
    GRADE NUMERIC(5, 2) NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);
